/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author maxid
 */
public class FrameVerRemitos extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrameVerRemitos
     */
    public FrameVerRemitos() {
        initComponents();
         ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtBuscarRemito = new javax.swing.JTextField();
        radioCliente = new javax.swing.JRadioButton();
        radioObra = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRemitos = new javax.swing.JTable();

        setBorder(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 74, 34));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 366, 13));

        txtBuscarRemito.setBackground(new java.awt.Color(0, 0, 0));
        txtBuscarRemito.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        txtBuscarRemito.setForeground(new java.awt.Color(255, 255, 255));
        txtBuscarRemito.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBuscarRemito.setBorder(null);
        jPanel1.add(txtBuscarRemito, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 370, 30));

        radioCliente.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(radioCliente);
        radioCliente.setForeground(new java.awt.Color(255, 255, 255));
        radioCliente.setSelected(true);
        radioCliente.setText("Cliente");
        jPanel1.add(radioCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 70, -1));

        radioObra.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(radioObra);
        radioObra.setForeground(new java.awt.Color(255, 255, 255));
        radioObra.setText("Obra");
        jPanel1.add(radioObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 80, -1));

        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        tablaRemitos.setForeground(new java.awt.Color(0, 0, 0));
        tablaRemitos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaRemitos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 600, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JRadioButton radioCliente;
    public javax.swing.JRadioButton radioObra;
    public javax.swing.JTable tablaRemitos;
    public javax.swing.JTextField txtBuscarRemito;
    // End of variables declaration//GEN-END:variables
}
