/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;

/**
 *
 * @author maxid
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
   
        
       
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new java.awt.Panel();
        panel1 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelNuevoCliente = new javax.swing.JLabel();
        labelCliente = new javax.swing.JLabel();
        labelNuevaObra = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelNuevoRemito = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblVerRemitos = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        escritorio = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel2.setBackground(new java.awt.Color(255, 255, 255));

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/negro/icons8-search-50.png"))); // NOI18N
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNuevoCliente.setForeground(new java.awt.Color(255, 255, 255));
        labelNuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/negro/icons8-contacts-50.png"))); // NOI18N
        labelNuevoCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelNuevoCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        labelNuevoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelNuevoClienteMousePressed(evt);
            }
        });
        jPanel1.add(labelNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 50, 70));

        labelCliente.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        labelCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCliente.setText("Cliente");
        jPanel1.add(labelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, 60));

        labelNuevaObra.setForeground(new java.awt.Color(255, 255, 255));
        labelNuevaObra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/negro/icons8-home-50.png"))); // NOI18N
        labelNuevaObra.setFocusable(false);
        labelNuevaObra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelNuevaObra.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(labelNuevaObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 60));

        jLabel4.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nueva obra");
        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 110, 60));

        labelNuevoRemito.setForeground(new java.awt.Color(255, 255, 255));
        labelNuevoRemito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/negro/icons8-document-50.png"))); // NOI18N
        labelNuevoRemito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelNuevoRemito.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(labelNuevoRemito, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 60));

        jLabel1.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Subir remitos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 110, 60));

        lblVerRemitos.setForeground(new java.awt.Color(255, 255, 255));
        lblVerRemitos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/negro/icons8-box-50.png"))); // NOI18N
        lblVerRemitos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblVerRemitos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(lblVerRemitos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 50));

        jLabel5.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ver Cta Corriente");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 160, 62));

        panel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        escritorio.setBackground(new java.awt.Color(51, 51, 51));
        escritorio.setPreferredSize(new java.awt.Dimension(629, 400));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 587, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel2Layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelNuevoClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNuevoClienteMousePressed
        
        labelCliente.setForeground(Color.CYAN);
    }//GEN-LAST:event_labelNuevoClienteMousePressed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCliente;
    public javax.swing.JLabel labelNuevaObra;
    public javax.swing.JLabel labelNuevoCliente;
    public javax.swing.JLabel labelNuevoRemito;
    public javax.swing.JLabel lblVerRemitos;
    public java.awt.Panel panel1;
    public java.awt.Panel panel2;
    // End of variables declaration//GEN-END:variables
    public FrameObra frameObra;
    public FrameVerRemitos frameRemitos=new FrameVerRemitos();
}
